module.exports = function() {
    return {
        local:{
            host:'localhost',
            port:3306,
            user:'test',
            password:'test',
            database:'test'
        },
        prod:{
            host:"",
            port:"",
            user:"",
            password:"",
            database:""
        },
        staging:{
            host:"",
            port:"",
            user:"",
            password:"",
            database:""
        },
        dev:{
            host:"",
            port:"",
            user:"",
            password:"",
            database:""
        },
    }
};